name: Sonar Cloud Scan  # Workflow name

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR open, sync, or reopen

jobs:
  sonarqube:
    name: SonarQube  # Job name for SonarQube analysis
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout Code  # Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for better analysis accuracy
      
      - name: SonarQube Scan  # Run SonarQube static code analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:        
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Secure authentication token for SonarQube
